// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code int    `json:"code"`
	Data string `json:"data"`
	Msg  string `json:"msg"`
}

type UserInfo struct {
	UserName string `json:"userName"`
	Addr     string `json:"addr"`
	Id       uint   `json:"id"`
}

type UserInfoRequest struct {
	Id int `json:"id"`
}

type UserInfoResponse struct {
	Code int      `json:"code"`
	Data UserInfo `json:"data"`
	Msg  string   `json:"msg"`
}
